version: 0.2
phases:
  install:
    runtime-versions:
        java: corretto8
  build:
    commands:
      - export BUCKET=lambda-function-bucket-mumbai
      - mvn -f firstcut/server/routing/pom.xml package shade:shade -Dmaven.test.skip=true 
      - aws s3 mv firstcut/server/routing/target/service-1.0.0.jar s3://lambda-function-bucket-mumbai
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
