version: 0.2
phases:
  install:
    runtime-versions:
        java: corretto8
  build:
    commands:
      - export BUCKET=lambda-function-bucket-mumbai
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - firstcut/server/template.yml
    - outputtemplate.yml
